opentelemetry-collector:
  mode: daemonset
  fullnameOverride: otel-collector-daemon
  service:
    enabled: true
    internalTrafficPolicy: Local
  config:
    exporters:
      otlp/gateway:
        endpoint: otel-collector-gateway.observability-sit.svc.cluster.local:4317
        tls:
          insecure: true
      debug:
        verbosity: normal
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp/gateway, debug]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp/gateway, debug]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp/gateway, debug]
