apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: otel-collector-daemon-sit
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: sit
            ns: observability-sit
  template:
    metadata:
      name: otel-collector-daemon-{{env}}
    spec:
      project: default
      source:
        repoURL: https://github.com/medstersrc/observability-gitops.git
        targetRevision: main
        path: helm/otel-collector
        helm:
          valueFiles:
            - values.yaml
            - values/{{env}}/daemon.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ns}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
