opentelemetry-collector:
  mode: deployment
  fullnameOverride: otel-collector-gateway
  replicaCount: 1

  config:
    exporters:
      otlp/newrelic:
        endpoint: ${env:NEW_RELIC_OTLP_ENDPOINT}
        headers:
          api-key: ${env:NEW_RELIC_API_KEY}
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [tail_sampling, memory_limiter, batch]
          exporters: [otlp/newrelic]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp/newrelic]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp/newrelic]

    processors:
      tail_sampling:
        decision_wait: 5s
        num_traces: 20000
        policies:
          - name: errors
            type: status_code
            status_code:
              status_codes: [ERROR]
          - name: baseline
            type: probabilistic
            probabilistic:
              sampling_percentage: 100

  extraEnvs:
    - name: NEW_RELIC_OTLP_ENDPOINT
      value: "https://otlp.eu01.nr-data.net:4317"
    - name: NEW_RELIC_API_KEY
      valueFrom:
        secretKeyRef:
          name: newrelic-otlp
          key: api-key
