apiVersion: v1
kind: Service
metadata:
  name: otel-collector-daemon
  namespace: observability-dev
spec:
  internalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/instance: otel-collector-daemon
    component: agent-collector
  ports:
    - name: otlp
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
