opentelemetry-collector:
  # Default mode to satisfy chart validation. Gateway overrides set deployment.
  mode: daemonset
  image:
    repository: otel/opentelemetry-collector-contrib
    tag: "0.77.0"

  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}

    processors:
      batch: {}

    exporters:
      logging:
        loglevel: info

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]

  ports:
    jaeger-compact:
      enabled: false
    jaeger-thrift:
      enabled: false
    jaeger-grpc:
      enabled: false
    zipkin:
      enabled: false
